/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante.view;
import restaurante.controller.ClienteController;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import restaurante.controller.CarrinhoController;
import restaurante.model.Clientes;
import restaurante.controller.ComprasController;
import restaurante.controller.PratosController;
import restaurante.model.Carrinho;
import restaurante.model.Compras;
import restaurante.model.Pratos;
/**
 *
 * @author 182210126
 */
public class JfRestaurante extends javax.swing.JFrame {

    /**
     * Creates new form JfRestaurante
     */
    public JfRestaurante() {
        initComponents();
    }
    String formaDePagamento;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        inputCpf = new javax.swing.JTextField();
        inputTelefone = new javax.swing.JTextField();
        inputEndereco = new javax.swing.JTextField();
        inputCadastrar = new javax.swing.JButton();
        inputAlterar = new javax.swing.JButton();
        outputPesquisar = new javax.swing.JButton();
        inputExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputListarCliente = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        inputPreco = new javax.swing.JTextField();
        inputPix = new javax.swing.JRadioButton();
        inputCredito = new javax.swing.JRadioButton();
        inputDebito = new javax.swing.JRadioButton();
        inputDinheiro = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        inputIdCliente = new javax.swing.JTextField();
        inputCadastrarCompra = new javax.swing.JButton();
        InputAlterarCompra = new javax.swing.JButton();
        inputPesquisarCompra = new javax.swing.JButton();
        inputDeletarCompra = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputListarCompra = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        inputPrato = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        InputPrecoPrato = new javax.swing.JTextField();
        inputCadastraPrato = new javax.swing.JButton();
        inputAlteraPrato = new javax.swing.JButton();
        outputPesquisaPrato = new javax.swing.JButton();
        inputExcluiPrato = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        outputListaPrato = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputTabelaCarrinho = new javax.swing.JTable();
        inputAdicionaCompraCarrinho = new javax.swing.JButton();
        InputRemoveCompraCarrinho = new javax.swing.JButton();
        inputFinalizaCompra = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        inputCodPratoCarrinho = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        inputCodCompraCarrinho = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(128, 0, 0));

        jPanel1.setBackground(new java.awt.Color(128, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cadastro de cliente");

        jLabel5.setText("Nome:");

        jLabel6.setText("cpf:");

        jLabel7.setText("Telefone:");

        jLabel8.setText("Endereço:");

        inputCadastrar.setText("Cadastrar");
        inputCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCadastrarActionPerformed(evt);
            }
        });

        inputAlterar.setText("Alterar");
        inputAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAlterarActionPerformed(evt);
            }
        });

        outputPesquisar.setText("Pesquisar");
        outputPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputPesquisarActionPerformed(evt);
            }
        });

        inputExcluir.setText("Excluir");
        inputExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputExcluirActionPerformed(evt);
            }
        });

        OutputListarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "CPF", "Telefone", "Endereço"
            }
        ));
        jScrollPane1.setViewportView(OutputListarCliente);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(inputNome))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(inputCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputEndereco)
                                .addComponent(inputTelefone)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inputCadastrar)
                        .addGap(79, 79, 79)
                        .addComponent(inputAlterar)
                        .addGap(83, 83, 83)
                        .addComponent(outputPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(inputExcluir)))
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(inputTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(inputEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCadastrar)
                    .addComponent(inputAlterar)
                    .addComponent(outputPesquisar)
                    .addComponent(inputExcluir))
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Cliente", jPanel1);

        jPanel2.setBackground(new java.awt.Color(128, 0, 0));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Cadastro de compra");

        jLabel10.setText("Preço total:");

        buttonGroup1.add(inputPix);
        inputPix.setText("Pix");
        inputPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPixActionPerformed(evt);
            }
        });

        buttonGroup1.add(inputCredito);
        inputCredito.setText("Crédito");
        inputCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCreditoActionPerformed(evt);
            }
        });

        buttonGroup1.add(inputDebito);
        inputDebito.setText("Débito");
        inputDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDebitoActionPerformed(evt);
            }
        });

        buttonGroup1.add(inputDinheiro);
        inputDinheiro.setText("Dinheiro");
        inputDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDinheiroActionPerformed(evt);
            }
        });

        jLabel11.setText("Codigo do cliente: ");

        inputCadastrarCompra.setText("Cadastrar");
        inputCadastrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCadastrarCompraActionPerformed(evt);
            }
        });

        InputAlterarCompra.setText("Alterar");
        InputAlterarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputAlterarCompraActionPerformed(evt);
            }
        });

        inputPesquisarCompra.setText("Pesquisar");
        inputPesquisarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPesquisarCompraActionPerformed(evt);
            }
        });

        inputDeletarCompra.setText("Deletar");
        inputDeletarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDeletarCompraActionPerformed(evt);
            }
        });

        outputListarCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idCompra", "Preço", "Forma de Pagmento", "fkCliente"
            }
        ));
        jScrollPane2.setViewportView(outputListarCompra);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(inputPix)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputCredito)
                        .addGap(95, 95, 95)
                        .addComponent(inputDebito)
                        .addGap(91, 91, 91)
                        .addComponent(inputDinheiro))
                    .addComponent(inputPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(inputCadastrarCompra)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(InputAlterarCompra)
                        .addGap(91, 91, 91)
                        .addComponent(inputPesquisarCompra)
                        .addGap(79, 79, 79)
                        .addComponent(inputDeletarCompra)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(226, 226, 226))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel9)
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(inputPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPix)
                    .addComponent(inputCredito)
                    .addComponent(inputDebito)
                    .addComponent(inputDinheiro))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(inputIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCadastrarCompra)
                    .addComponent(InputAlterarCompra)
                    .addComponent(inputPesquisarCompra)
                    .addComponent(inputDeletarCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Compra", jPanel2);

        jPanel3.setBackground(new java.awt.Color(128, 0, 0));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Cadastro de prato");

        jLabel13.setText("Prato:");

        jLabel14.setText("preco do prato:");

        inputCadastraPrato.setText("Cadastrar");
        inputCadastraPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCadastraPratoActionPerformed(evt);
            }
        });

        inputAlteraPrato.setText("Alterar");
        inputAlteraPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAlteraPratoActionPerformed(evt);
            }
        });

        outputPesquisaPrato.setText("Pesquisar");
        outputPesquisaPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputPesquisaPratoActionPerformed(evt);
            }
        });

        inputExcluiPrato.setText("Excluir");
        inputExcluiPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputExcluiPratoActionPerformed(evt);
            }
        });

        outputListaPrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idPrato", "Prato", "Preço"
            }
        ));
        jScrollPane4.setViewportView(outputListaPrato);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(inputCadastraPrato)
                .addGap(60, 60, 60)
                .addComponent(inputAlteraPrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(outputPesquisaPrato)
                .addGap(78, 78, 78)
                .addComponent(inputExcluiPrato)
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(InputPrecoPrato))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(inputPrato, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel12)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(inputPrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(InputPrecoPrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputCadastraPrato)
                    .addComponent(inputAlteraPrato)
                    .addComponent(outputPesquisaPrato)
                    .addComponent(inputExcluiPrato))
                .addGap(89, 89, 89))
        );

        jTabbedPane1.addTab("Pratos", jPanel3);

        jPanel4.setBackground(new java.awt.Color(128, 0, 0));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Carrinho de compras");

        outputTabelaCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo da compra", "Codigo do prato", "Nome do prato", "Preço do prato"
            }
        ));
        jScrollPane3.setViewportView(outputTabelaCarrinho);

        inputAdicionaCompraCarrinho.setText("+");
        inputAdicionaCompraCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAdicionaCompraCarrinhoActionPerformed(evt);
            }
        });

        InputRemoveCompraCarrinho.setText("-");
        InputRemoveCompraCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputRemoveCompraCarrinhoActionPerformed(evt);
            }
        });

        inputFinalizaCompra.setText("Finalizar compra");
        inputFinalizaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFinalizaCompraActionPerformed(evt);
            }
        });

        jLabel16.setText("Codigo do prato a ser adicionado a compra:");

        jLabel17.setText("Codigo da compra:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(207, 207, 207))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(inputFinalizaCompra))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputRemoveCompraCarrinho)
                            .addComponent(inputAdicionaCompraCarrinho)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(inputCodCompraCarrinho))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(inputCodPratoCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel15)
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(inputCodPratoCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(inputCodCompraCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(inputAdicionaCompraCarrinho)
                        .addGap(18, 18, 18)
                        .addComponent(InputRemoveCompraCarrinho)))
                .addGap(41, 41, 41)
                .addComponent(inputFinalizaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Carrinho", jPanel4);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restauranteImagem/logorestaurante (1).png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel1.setText("Shan liàng de jīdàn");

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel3.setText("Delicias asiaticas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(29, 29, 29)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Cliente");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCadastrarActionPerformed
        ClienteController clicon = new ClienteController();
        clicon.cadastrarCliente(inputNome.getText(), inputCpf.getText(), inputTelefone.getText(), inputEndereco.getText());
        
    }//GEN-LAST:event_inputCadastrarActionPerformed

    private void inputAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAlterarActionPerformed
        
        JfAlteraCliente jfAlteraC= new JfAlteraCliente();
        jfAlteraC.setVisible(true);
        jfAlteraC.setSize(400, 238);
        jfAlteraC.setDefaultCloseOperation(jfAlteraC.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_inputAlterarActionPerformed

    private void inputExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputExcluirActionPerformed
        ClienteController clicon = new ClienteController();
        int idCliente = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite o codigo do cliente que deseja excluir"));
        clicon.excluirCliente(idCliente);
    }//GEN-LAST:event_inputExcluirActionPerformed

    private void outputPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputPesquisarActionPerformed
        ClienteController clicon = new ClienteController();
        ArrayList<Clientes> listaCliente = clicon.listarCliente();
       
        DefaultTableModel model = (DefaultTableModel) OutputListarCliente.getModel();
        model.setNumRows(0);
        String[] coluna  = {"","","","",""};
        for(Clientes cli:listaCliente){
        coluna[0] = String.valueOf(cli.getIdCliente());
        coluna[1] = String.valueOf(cli.getNome());
        coluna[2] = String.valueOf(cli.getCpf());
        coluna[3] = String.valueOf(cli.getTelefone());
        coluna[4] = String.valueOf(cli.getEndereco());
        model.addRow(coluna);
        }
    }//GEN-LAST:event_outputPesquisarActionPerformed

    private void inputCadastrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCadastrarCompraActionPerformed
        ComprasController comcon = new ComprasController();
        comcon.cadastrarCompra(Float.parseFloat(inputPreco.getText()), formaDePagamento, Integer.parseInt(inputIdCliente.getText()));
    }//GEN-LAST:event_inputCadastrarCompraActionPerformed

    private void inputPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPixActionPerformed
        formaDePagamento = "Pix";
    }//GEN-LAST:event_inputPixActionPerformed

    private void inputCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCreditoActionPerformed
        formaDePagamento = "Crédito";
    }//GEN-LAST:event_inputCreditoActionPerformed

    private void inputDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDebitoActionPerformed
        formaDePagamento = "Débito";
    }//GEN-LAST:event_inputDebitoActionPerformed

    private void inputDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDinheiroActionPerformed
        formaDePagamento = "Dinheiro";
    }//GEN-LAST:event_inputDinheiroActionPerformed

    private void InputAlterarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputAlterarCompraActionPerformed
        JfAlteraCompra jfAlteraComp= new JfAlteraCompra();
        jfAlteraComp.setVisible(true);
        jfAlteraComp.setSize(380, 300);
        jfAlteraComp.setDefaultCloseOperation(jfAlteraComp.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_InputAlterarCompraActionPerformed

    private void inputDeletarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDeletarCompraActionPerformed
        ComprasController comcon = new ComprasController();
        int idCompra = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite o codigo da compra que deseja excluir"));
        comcon.excluirCompra(idCompra);
    }//GEN-LAST:event_inputDeletarCompraActionPerformed

    private void inputPesquisarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPesquisarCompraActionPerformed
       ComprasController comcon = new ComprasController();
        ArrayList<Compras> listaCompra = comcon.listarCompra();
       
        DefaultTableModel model = (DefaultTableModel) outputListarCompra.getModel();
        model.setNumRows(0);
        String[] coluna  = {"","","",""};
        for(Compras comp:listaCompra){
        coluna[0] = String.valueOf(comp.getIdCompra());
        coluna[1] = String.valueOf(comp.getPreco());
        coluna[2] = String.valueOf(comp.getFormaDePagamento());
        coluna[3] = String.valueOf(comp.getFkCliente());
        model.addRow(coluna);
        }
    }//GEN-LAST:event_inputPesquisarCompraActionPerformed

    private void inputCadastraPratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCadastraPratoActionPerformed
        PratosController pracon = new PratosController();
        pracon.cadastrarPrato(inputPrato.getText(), Float.parseFloat(InputPrecoPrato.getText()));
    }//GEN-LAST:event_inputCadastraPratoActionPerformed

    private void inputExcluiPratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputExcluiPratoActionPerformed
         PratosController pracon = new PratosController();
        int idPrato = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite o codigo do prato que deseja excluir"));
        pracon.excluirPrato(idPrato);
    }//GEN-LAST:event_inputExcluiPratoActionPerformed

    private void inputAlteraPratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAlteraPratoActionPerformed
        JfAlteraPrato jfAlteraPra= new JfAlteraPrato();
        jfAlteraPra.setVisible(true);
        jfAlteraPra.setSize(400, 212);
        jfAlteraPra.setDefaultCloseOperation(jfAlteraPra.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_inputAlteraPratoActionPerformed

    private void outputPesquisaPratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputPesquisaPratoActionPerformed
        PratosController pracon = new PratosController();
        ArrayList<Pratos> listaPrato = pracon.listarPrato();
        
        DefaultTableModel model = (DefaultTableModel) outputListaPrato.getModel();
        model.setNumRows(0);
        String[] coluna = {"","",""};
        for(Pratos pra:listaPrato){
        coluna[0] = String.valueOf(pra.getIdPrato());
        coluna[1] = String.valueOf(pra.getPrato());
        coluna[2] = String.valueOf(pra.getPreco());
        
        model.addRow(coluna);
        }
    }//GEN-LAST:event_outputPesquisaPratoActionPerformed

    private void InputRemoveCompraCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputRemoveCompraCarrinhoActionPerformed
        DefaultTableModel model = (DefaultTableModel) outputTabelaCarrinho.getModel(); 
        model.removeRow(outputTabelaCarrinho.getSelectedRow());
    }//GEN-LAST:event_InputRemoveCompraCarrinhoActionPerformed

    private void inputAdicionaCompraCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAdicionaCompraCarrinhoActionPerformed
         CarrinhoController carcon = new CarrinhoController();
         ArrayList<Carrinho> listarCarrinho = carcon.listarCarrinho(Integer.parseInt(inputCodPratoCarrinho.getText()),Integer.parseInt(inputCodCompraCarrinho.getText()));
         
         DefaultTableModel model = (DefaultTableModel) outputTabelaCarrinho.getModel();
         model.setNumRows(0);
          String[] coluna = {"","","",""};
        for(Carrinho car:listarCarrinho){
        coluna[0] = String.valueOf(car.getCodCompra());
        coluna[1] = String.valueOf(car.getCodPrato());
        coluna[2] = String.valueOf(car.getNomePrato());
        coluna[3] = String.valueOf(car.getPrecoPrato());
        model.addRow(coluna);
        }
    }//GEN-LAST:event_inputAdicionaCompraCarrinhoActionPerformed

    private void inputFinalizaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFinalizaCompraActionPerformed
        CarrinhoController carcon = new CarrinhoController();
        carcon.finalizarCompra(Integer.parseInt(inputCodPratoCarrinho.getText()),Integer.parseInt(inputCodCompraCarrinho.getText()));
    }//GEN-LAST:event_inputFinalizaCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfRestaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InputAlterarCompra;
    private javax.swing.JTextField InputPrecoPrato;
    private javax.swing.JButton InputRemoveCompraCarrinho;
    private javax.swing.JTable OutputListarCliente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton inputAdicionaCompraCarrinho;
    private javax.swing.JButton inputAlteraPrato;
    private javax.swing.JButton inputAlterar;
    private javax.swing.JButton inputCadastraPrato;
    private javax.swing.JButton inputCadastrar;
    private javax.swing.JButton inputCadastrarCompra;
    private javax.swing.JTextField inputCodCompraCarrinho;
    private javax.swing.JTextField inputCodPratoCarrinho;
    private javax.swing.JTextField inputCpf;
    private javax.swing.JRadioButton inputCredito;
    private javax.swing.JRadioButton inputDebito;
    private javax.swing.JButton inputDeletarCompra;
    private javax.swing.JRadioButton inputDinheiro;
    private javax.swing.JTextField inputEndereco;
    private javax.swing.JButton inputExcluiPrato;
    private javax.swing.JButton inputExcluir;
    private javax.swing.JButton inputFinalizaCompra;
    private javax.swing.JTextField inputIdCliente;
    private javax.swing.JTextField inputNome;
    private javax.swing.JButton inputPesquisarCompra;
    private javax.swing.JRadioButton inputPix;
    private javax.swing.JTextField inputPrato;
    private javax.swing.JTextField inputPreco;
    private javax.swing.JTextField inputTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable outputListaPrato;
    private javax.swing.JTable outputListarCompra;
    private javax.swing.JButton outputPesquisaPrato;
    private javax.swing.JButton outputPesquisar;
    private javax.swing.JTable outputTabelaCarrinho;
    // End of variables declaration//GEN-END:variables
}
